site_name: CartaNatal.de
site_url: https://CartaNatal.de
site_author: "Jim Raynor"
#edit_uri: ""
repo_url: /servicios/carta-natal-personalizada/
repo_name: Haz mi Carta Natal

theme:
  name: material
  language: es
  logo: assets/1px.png
  
  custom_dir: overrides
 # palette:
    # Modo claro (fondo claro -> colores oscuros)
  #  - scheme: default
   #   primary: custom     # usaremos nuestro color personalizado
    #  accent: custom      # también personalizado
     # toggle:
      #  icon: material/brightness-4
       # name: Cambiar a modo oscuro
    # Modo oscuro (fondo oscuro -> colores claros)
   # - scheme: slate
    #  primary: custom
     # accent: custom
      #toggle:
       # icon: material/brightness-7
        #name: Cambiar a modo claro
  icon:
    repo: material/brightness-7
  favicon: material/brightness-7
  highlightjs: true
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - search.term.highlight
    - content.code.copy
    - content.code.select
    - content.code.scroll
    - content.code.line-numbers
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
    - navigation.instant
    - navigation.path
    - navigation.tracking

extra_css:
  - assets/stylesheets/extra.css
  #- assets/stylesheets/cartanatal.css   # <--- NUEVO: el archivo de estilos personalizados
  # - assets/stylesheets/kofi.css       # si lo necesitas, lo dejas comentado o lo añades

plugins:
  - search
  - ezlinks
  - encryptcontent:
      password_file: 'passwords.yml'
      webcrypto: true
      kdf_pow: 2
      remember_keys: true
      remember_password: false
      password_button: True
      password_button_text: 'Desbloquear'
      placeholder: 'Contraseña'
      placeholder_user: 'Usuario'
      summary: '⚠️ Esta página está protegida.'
      decryption_failure_message: '❌ Credenciales incorrectas. Si el problema persiste, recarga la página e inténtalo de nuevo.'
      encryption_info_message: '🔒 Necesitas credenciales para ver este contenido.'
      encrypted_something:
        main: [main, tag]
 # - section-index
  - rss:
      match_path: "AstroMitos/.*"
      date_from_meta:
        as_creation: date
        as_update: false
      length: 20
      abstract_chars_count: 160
  - glightbox
  - mkdocs-video

copyright: "✦ CartaNatal.de - Astrología esencial ✦ Hecho con 💙 por Jim Raynor - 2026"
extra:
  author: "Jim Raynor"
  link: "https://CartaNatal.de"
  avatar: "docs/assets/logo.jpg"
  year: 2026
  generator: false
  social:
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/jimraynor88
      name: KeyBase
    - icon: fontawesome/brands/telegram
      link: https://t.me/jimraynorbot
      name: Telegram
    - icon: fontawesome/solid/sitemap
      link: /sitemap.xml
      name: Mapa del sitio
    - icon: fontawesome/solid/mug-hot
      link: https://ko-fi.com/invito/?hidefeed=true&widget=true
      name: Invítame al Ko-Fi

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.superfences
  - tables
  - attr_list
  - pymdownx.blocks.html
  - pymdownx.emoji:
     emoji_index: !!python/name:material.extensions.emoji.twemoji
     emoji_generator: !!python/name:material.extensions.emoji.to_svg
