name: Deploy MkDocs

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

  #    - name: Generate shop data
   #     run: python scripts/generar_tienda.py

      - name: Build site
        run: mkdocs build

      - name: Add global prev/next links
        run: python scripts/add_prev_next_global.py site
        
      - name: Create MTA-STS and .nojekyll
        run: |
          mkdir -p site/.well-known
          cat > site/.well-known/mta-sts.txt << 'EOF'
          version: STSv1
          mode: enforce
          mx: route3.mx.cloudflare.net
          mx: route1.mx.cloudflare.net
          mx: route2.mx.cloudflare.net
          max_age: 604800
          EOF
          touch site/.nojekyll
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
